""" ss.py

    Most content mercilessly and unrepentantly pirated from
    http://benedictcumberbatchgenerator.tumblr.com/
"""

firstnames = (
    "Anglerfish",
    "Bakery",
    "Bandersnatch",
    "Bandicoot",
    "Barister",
    "Barnoldswick",
    "Baseballbat",
    "Baseballmitt",
    "Bedlington",
    "Beetlejuice",
    "Beezlebub",
    "Benadryl",
    "Bendandsnap",
    "Benetton",
    "Benjamin",
    "Bentobox",
    "Bentobox",
    "Billiardball",
    "Billyray",
    "Blasphemy",
    "Blubberwhale",
    "Bodybuild",
    "Boilerdang",
    "Bombadil",
    "Bombadil",
    "Bonaparte",
    "Boobytrap",
    "Bouillabaisse",
    "Bourgeoisie",
    "Brandenburg",
    "Brandybuck",
    "Brewery",
    "Broccoli",
    "Buckingham",
    "Buckminster",
    "Buckyball",
    "Budapest",
    "Buffalo",
    "Bulbasaur",
    "Bumberstump",
    "Bumblebee",
    "Bumbleshack",
    "Bunsenburner",
    "Burberry",
    "Burgerking",
    "Burlington",
    "Buttercup",
    "Butterfree",
    "Buttermilk",
    "Cogglesnatch",
    "Congleton",
    "Danglerack",
    "Fragglerock",
    "Honkytonk",
    "Johnnycash",
    "Liverswort",
    "Muffintop",
    "Oscarbait",
    "Pallettown",
    "Rinkydink",
    "Rumblesack",
    "Snorkeldink",
    "Snozzlebert",
    "Tiddleywomp",
    "Timothy",
    "Wellington",
    "Whippersnatch",
    "Wimbledon"
)

firstnames_unclean = (
    "Anallube",
    "Barbituate",
    "Bendydick",
    "Blenderdick",
    "Blubberbutt",
    "Blubberdick",
    "Bukkake",
    "Syphilis"
)

lastnames = (
    "Ampersand",
    "Animorph",
    "Banglesnatch",
    "Battleship",
    "Bumbersplat",
    "Cabbagepatch",
    "Calldispatch",
    "Camouflage",
    "Candlestick",
    "Candycrush",
    "Candygram",
    "Cankersore",
    "Capncrunch",
    "Carrotstick",
    "Charizard",
    "Cheddarcheese",
    "Chesterfield",
    "Chickenbroth",
    "Chickenstrips",
    "Chowderpants",
    "Chuckecheese",
    "Clavichord",
    "Clombyclomp",
    "Coddleswort",
    "Coggleswort",
    "Collywog",
    "Colonist",
    "Commonwealth",
    "Concubine",
    "Copperwire",
    "Cottagecheese",
    "Countryside",
    "Covergirl",
    "Crackerjack",
    "Crackersprout",
    "Cragglethatch",
    "Creamsicle",
    "Crimpysnitch",
    "Crucifix",
    "Crumplebutt",
    "Crumplehorn",
    "Crumplesack",
    "Cuckatoo",
    "Cuckooclock",
    "Cumberbund",
    "Cumbersnatch",
    "Cumbersome",
    "Cummerbund",
    "Cunningsnatch",
    "Curdledmilk",
    "Curdlemilk",
    "Curdlesnoot",
    "Custardbath",
    "Cuttlefish",
    "Frumblesnatch",
    "Humperdinck",
    "Kryptonite",
    "Lingerie",
    "Moldyspore",
    "Nottinghill",
    "Oxfordshire",
    "Rivendell",
    "Scratchnsniff",
    "Snickersbar",
    "Snugglesnatch",
    "Splishnsplash",
    "Stinkyrash",
    "Talisman",
    "Toodlesnoot",
    "Upperclass",
    "Vegemite",
    "Wafflesmack"
)

lastnames_unclean = (
    "Cameltoe",
    "Cockletit",
    "Coochierash",
    "Crackerdong",
    "Cumbercooch",
    "Curdledong"
)

fullnames = (
    "Benadryl Claritin",
    "Benedict Timothy Carlton Cumberbatch",
    "Biblical Concubine",
    "Bombadil Rivendell",
    "Bourgeoisie Capitas",
    "Buckminster Fullerene",
    "Butawhiteboy Cantbekhan",
    "Rinkydink Curdlesnoot",
    "Wanda's Son",
    "Wimbledon Tennismatch"
)

fullnames_unclean = (
    "Syphilis Cankersore",
    "Wanda's Crotchfruit"
)
